// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: mediaServerMsg.proto

package protobuf

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Payload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *Payload) Reset() {
	*x = Payload{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mediaServerMsg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payload) ProtoMessage() {}

func (x *Payload) ProtoReflect() protoreflect.Message {
	mi := &file_mediaServerMsg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payload.ProtoReflect.Descriptor instead.
func (*Payload) Descriptor() ([]byte, []int) {
	return file_mediaServerMsg_proto_rawDescGZIP(), []int{0}
}

func (x *Payload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_mediaServerMsg_proto protoreflect.FileDescriptor

var file_mediaServerMsg_proto_rawDesc = []byte{
	0x0a, 0x14, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d, 0x73, 0x67,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x22, 0x23, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x4e, 0x0a, 0x0a, 0x4d, 0x65, 0x64, 0x69, 0x61, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x40, 0x0a, 0x10, 0x62, 0x69, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x2e, 0x73, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x1a, 0x12, 0x2e, 0x73,
	0x61, 0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x2e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mediaServerMsg_proto_rawDescOnce sync.Once
	file_mediaServerMsg_proto_rawDescData = file_mediaServerMsg_proto_rawDesc
)

func file_mediaServerMsg_proto_rawDescGZIP() []byte {
	file_mediaServerMsg_proto_rawDescOnce.Do(func() {
		file_mediaServerMsg_proto_rawDescData = protoimpl.X.CompressGZIP(file_mediaServerMsg_proto_rawDescData)
	})
	return file_mediaServerMsg_proto_rawDescData
}

var file_mediaServerMsg_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mediaServerMsg_proto_goTypes = []interface{}{
	(*Payload)(nil), // 0: samespace.payload
}
var file_mediaServerMsg_proto_depIdxs = []int32{
	0, // 0: samespace.Mediaproto.biCommonExchange:input_type -> samespace.payload
	0, // 1: samespace.Mediaproto.biCommonExchange:output_type -> samespace.payload
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mediaServerMsg_proto_init() }
func file_mediaServerMsg_proto_init() {
	if File_mediaServerMsg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mediaServerMsg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payload); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mediaServerMsg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mediaServerMsg_proto_goTypes,
		DependencyIndexes: file_mediaServerMsg_proto_depIdxs,
		MessageInfos:      file_mediaServerMsg_proto_msgTypes,
	}.Build()
	File_mediaServerMsg_proto = out.File
	file_mediaServerMsg_proto_rawDesc = nil
	file_mediaServerMsg_proto_goTypes = nil
	file_mediaServerMsg_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MediaprotoClient is the client API for Mediaproto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MediaprotoClient interface {
	//bi directional rpc
	BiCommonExchange(ctx context.Context, opts ...grpc.CallOption) (Mediaproto_BiCommonExchangeClient, error)
}

type mediaprotoClient struct {
	cc grpc.ClientConnInterface
}

func NewMediaprotoClient(cc grpc.ClientConnInterface) MediaprotoClient {
	return &mediaprotoClient{cc}
}

func (c *mediaprotoClient) BiCommonExchange(ctx context.Context, opts ...grpc.CallOption) (Mediaproto_BiCommonExchangeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Mediaproto_serviceDesc.Streams[0], "/samespace.Mediaproto/biCommonExchange", opts...)
	if err != nil {
		return nil, err
	}
	x := &mediaprotoBiCommonExchangeClient{stream}
	return x, nil
}

type Mediaproto_BiCommonExchangeClient interface {
	Send(*Payload) error
	Recv() (*Payload, error)
	grpc.ClientStream
}

type mediaprotoBiCommonExchangeClient struct {
	grpc.ClientStream
}

func (x *mediaprotoBiCommonExchangeClient) Send(m *Payload) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mediaprotoBiCommonExchangeClient) Recv() (*Payload, error) {
	m := new(Payload)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MediaprotoServer is the server API for Mediaproto service.
type MediaprotoServer interface {
	//bi directional rpc
	BiCommonExchange(Mediaproto_BiCommonExchangeServer) error
}

// UnimplementedMediaprotoServer can be embedded to have forward compatible implementations.
type UnimplementedMediaprotoServer struct {
}

func (*UnimplementedMediaprotoServer) BiCommonExchange(Mediaproto_BiCommonExchangeServer) error {
	return status.Errorf(codes.Unimplemented, "method BiCommonExchange not implemented")
}

func RegisterMediaprotoServer(s *grpc.Server, srv MediaprotoServer) {
	s.RegisterService(&_Mediaproto_serviceDesc, srv)
}

func _Mediaproto_BiCommonExchange_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MediaprotoServer).BiCommonExchange(&mediaprotoBiCommonExchangeServer{stream})
}

type Mediaproto_BiCommonExchangeServer interface {
	Send(*Payload) error
	Recv() (*Payload, error)
	grpc.ServerStream
}

type mediaprotoBiCommonExchangeServer struct {
	grpc.ServerStream
}

func (x *mediaprotoBiCommonExchangeServer) Send(m *Payload) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mediaprotoBiCommonExchangeServer) Recv() (*Payload, error) {
	m := new(Payload)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Mediaproto_serviceDesc = grpc.ServiceDesc{
	ServiceName: "samespace.Mediaproto",
	HandlerType: (*MediaprotoServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "biCommonExchange",
			Handler:       _Mediaproto_BiCommonExchange_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "mediaServerMsg.proto",
}
