// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: mediafun.proto

package say

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Sdp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fromid    string `protobuf:"bytes,1,opt,name=fromid,proto3" json:"fromid,omitempty"`
	Toid      string `protobuf:"bytes,2,opt,name=toid,proto3" json:"toid,omitempty"`
	Offer     string `protobuf:"bytes,3,opt,name=offer,proto3" json:"offer,omitempty"`
	Sessionid string `protobuf:"bytes,4,opt,name=sessionid,proto3" json:"sessionid,omitempty"`
}

func (x *Sdp) Reset() {
	*x = Sdp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_mediafun_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sdp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sdp) ProtoMessage() {}

func (x *Sdp) ProtoReflect() protoreflect.Message {
	mi := &file_mediafun_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sdp.ProtoReflect.Descriptor instead.
func (*Sdp) Descriptor() ([]byte, []int) {
	return file_mediafun_proto_rawDescGZIP(), []int{0}
}

func (x *Sdp) GetFromid() string {
	if x != nil {
		return x.Fromid
	}
	return ""
}

func (x *Sdp) GetToid() string {
	if x != nil {
		return x.Toid
	}
	return ""
}

func (x *Sdp) GetOffer() string {
	if x != nil {
		return x.Offer
	}
	return ""
}

func (x *Sdp) GetSessionid() string {
	if x != nil {
		return x.Sessionid
	}
	return ""
}

var File_mediafun_proto protoreflect.FileDescriptor

var file_mediafun_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x66, 0x75, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x73, 0x61, 0x79, 0x22, 0x65, 0x0a, 0x03, 0x73, 0x64, 0x70, 0x12, 0x16, 0x0a, 0x06,
	0x66, 0x72, 0x6f, 0x6d, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x72,
	0x6f, 0x6d, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x6f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x74, 0x6f, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x66, 0x66, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x66, 0x66, 0x65, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x69, 0x64, 0x32, 0x2f, 0x0a, 0x08,
	0x4d, 0x61, 0x6b, 0x65, 0x63, 0x61, 0x6c, 0x6c, 0x12, 0x23, 0x0a, 0x0b, 0x73, 0x64, 0x70, 0x65,
	0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x08, 0x2e, 0x73, 0x61, 0x79, 0x2e, 0x73, 0x64,
	0x70, 0x1a, 0x08, 0x2e, 0x73, 0x61, 0x79, 0x2e, 0x73, 0x64, 0x70, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_mediafun_proto_rawDescOnce sync.Once
	file_mediafun_proto_rawDescData = file_mediafun_proto_rawDesc
)

func file_mediafun_proto_rawDescGZIP() []byte {
	file_mediafun_proto_rawDescOnce.Do(func() {
		file_mediafun_proto_rawDescData = protoimpl.X.CompressGZIP(file_mediafun_proto_rawDescData)
	})
	return file_mediafun_proto_rawDescData
}

var file_mediafun_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_mediafun_proto_goTypes = []interface{}{
	(*Sdp)(nil), // 0: say.sdp
}
var file_mediafun_proto_depIdxs = []int32{
	0, // 0: say.Makecall.sdpexchange:input_type -> say.sdp
	0, // 1: say.Makecall.sdpexchange:output_type -> say.sdp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mediafun_proto_init() }
func file_mediafun_proto_init() {
	if File_mediafun_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_mediafun_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sdp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_mediafun_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mediafun_proto_goTypes,
		DependencyIndexes: file_mediafun_proto_depIdxs,
		MessageInfos:      file_mediafun_proto_msgTypes,
	}.Build()
	File_mediafun_proto = out.File
	file_mediafun_proto_rawDesc = nil
	file_mediafun_proto_goTypes = nil
	file_mediafun_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MakecallClient is the client API for Makecall service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MakecallClient interface {
	Sdpexchange(ctx context.Context, in *Sdp, opts ...grpc.CallOption) (*Sdp, error)
}

type makecallClient struct {
	cc grpc.ClientConnInterface
}

func NewMakecallClient(cc grpc.ClientConnInterface) MakecallClient {
	return &makecallClient{cc}
}

func (c *makecallClient) Sdpexchange(ctx context.Context, in *Sdp, opts ...grpc.CallOption) (*Sdp, error) {
	out := new(Sdp)
	err := c.cc.Invoke(ctx, "/say.Makecall/sdpexchange", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MakecallServer is the server API for Makecall service.
type MakecallServer interface {
	Sdpexchange(context.Context, *Sdp) (*Sdp, error)
}

// UnimplementedMakecallServer can be embedded to have forward compatible implementations.
type UnimplementedMakecallServer struct {
}

func (*UnimplementedMakecallServer) Sdpexchange(context.Context, *Sdp) (*Sdp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sdpexchange not implemented")
}

func RegisterMakecallServer(s *grpc.Server, srv MakecallServer) {
	s.RegisterService(&_Makecall_serviceDesc, srv)
}

func _Makecall_Sdpexchange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Sdp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MakecallServer).Sdpexchange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/say.Makecall/Sdpexchange",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MakecallServer).Sdpexchange(ctx, req.(*Sdp))
	}
	return interceptor(ctx, in, info, handler)
}

var _Makecall_serviceDesc = grpc.ServiceDesc{
	ServiceName: "say.Makecall",
	HandlerType: (*MakecallServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "sdpexchange",
			Handler:    _Makecall_Sdpexchange_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mediafun.proto",
}
